id: P009660
initial_creation_type: ocr
source_metadata:
  id: bdr:W23387
  title: ཤཱཀྱ་བསྟན་འཛིན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    8f784f2d309e4ab396ec13fe558ba99d:
      image_group_id: I1935
      title: ''
      volume_number: 1
      total_pages: 414
